// <auto-generated />
namespace TMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2016091101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2016091101));
        
        string IMigrationMetadata.Id
        {
            get { return "201609102042494_2016091101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
