 using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TMS.Model;

namespace TMS.DAL
{
    public class TMSEntitiesInitializer : CreateDatabaseIfNotExists<TMSEntities>
    {
        protected override void Seed(TMSEntities context)
        {
            CheckExistenceOfRoles(context);
            BuildTempMenus(context);
            CreateUsers(context);
            context.SaveChanges();
            base.Seed(context);
        }
       
        private void CheckExistenceOfRoles(TMSEntities context)
        {
            var roles = context.Roles.ToList();
            if (!roles.Any(role => role.Name == "Admin"))
                CreateRole(1, "Admin", "Super User", context);
            if (!roles.Any(role => role.Name == "Distributor"))
                CreateRole(2, "Distributor", "User with moderate privileges", context);
            if (!roles.Any(role => role.Name == "Dealer"))
                CreateRole(3, "Dealer", "User with less privileges", context);
            if (!roles.Any(role => role.Name == "Customer"))
                CreateRole(4, "Customer", "Basic user privileges", context);
        }

        private void CreateRole(int roleId, string roleName, string description, TMSEntities context)
        {
            Role role = new Role() { RoleId = roleId, Name = roleName, Description = description };
            context.Roles.Add(role);
        }

        private void BuildTempMenus(TMSEntities context)
        {
            List<Menu> menus = new List<Menu>()
            {
                new Menu { MenuId = 1, Name = "Admin Menus" },
                new Menu { MenuId = 2, Name = "Distrbutor Menus" },
                new Menu { MenuId = 3, Name = "Dealer Menus" },
                new Menu { MenuId = 4, Name = "Customer Menus" }

            };
            context.Menus.AddRange(menus);

            List<MenuItem> menuItems = new List<MenuItem>()
            {
                // Main Menus List - For Admin Menus
                new MenuItem { MenuItemId = 1, MenuId = 1, Text = "Dashboard", Action = "", Controller ="", URL = "#", MenuOrder = 1, CSSClass = "fa fa-dashboard", Enabled = true },
                new MenuItem { MenuItemId = 2, MenuId = 1, Text = "Masters", Action = "", Controller ="", URL = "#", MenuOrder = 2, CSSClass = "fa fa-pie-chart", Enabled = true },
                new MenuItem { MenuItemId = 3, MenuId = 1, Text = "Alert Management", Action = "Index", Controller ="Alerts", URL = "", MenuOrder = 3, CSSClass = "fa fa-files-o", Enabled = true },
                new MenuItem { MenuItemId = 4, MenuId = 1, Text = "Reports", Action = "", Controller ="", URL = "#", MenuOrder = 4, CSSClass = "fa fa-th", Enabled = true },
                new MenuItem { MenuItemId = 5, MenuId = 1, Text = "User Management", Action = "", Controller ="", URL = "#", MenuOrder = 5, CSSClass = "fa fa-laptop", Enabled = true },
                //new MenuItem { MenuItemId = 6, MenuId = 1, Text = "Categories Management", Action = "", Controller ="", URL = "#", MenuOrder = 6, CSSClass = "fa fa-edit", Enabled = true },
                new MenuItem { MenuItemId = 7, MenuId = 1, Text = "Server Management",  URL = "#", MenuOrder = 7, CSSClass = "fa fa-table", Enabled = true },
                new MenuItem { MenuItemId = 8, MenuId = 1, Text = "Vehicles Online", Action = "", Controller ="", URL = "#", MenuOrder = 8, CSSClass = "fa fa-calendar", Enabled = true },
                //new MenuItem { MenuItemId = 9, MenuId = 1, Text = "Gallery Management", Action = "", Controller ="", URL = "#", MenuOrder = 9, CSSClass = "fa fa-folder", Enabled = true },

                // Main Menus List - For Distrbutor Menus
                new MenuItem { MenuItemId = 10, MenuId = 2, Text = "Dashboard", Action = "", Controller ="", URL = "#", MenuOrder = 1, CSSClass = "fa fa-dashboard", Enabled = true },
                new MenuItem { MenuItemId = 11, MenuId = 2, Text = "Masters", Action = "", Controller ="", URL = "#", MenuOrder = 2, CSSClass = "fa fa-pie-chart", Enabled = true },
                new MenuItem { MenuItemId = 12, MenuId = 2, Text = "Alert Management", Action = "", Controller ="", URL = "#", MenuOrder = 3, CSSClass = "fa fa-files-o", Enabled = true },
                new MenuItem { MenuItemId = 13, MenuId = 2, Text = "Reports", Action = "", Controller ="", URL = "#", MenuOrder = 4, CSSClass = "fa fa-th", Enabled = true },
                //new MenuItem { MenuItemId = 5, MenuId = 2, Text = "User Management", Action = "", Controller ="", URL = "#", MenuOrder = 5, CSSClass = "fa fa-laptop", Enabled = true },
                //new MenuItem { MenuItemId = 6, MenuId = 2, Text = "Categories Management", Action = "", Controller ="", URL = "#", MenuOrder = 6, CSSClass = "fa fa-edit", Enabled = true },
                //new MenuItem { MenuItemId = 7, MenuId = 2, Text = "Server Management",  URL = "#", MenuOrder = 7, CSSClass = "fa fa-table", Enabled = true },
                new MenuItem { MenuItemId = 14, MenuId = 2, Text = "Vehicles Online", Action = "", Controller ="", URL = "#", MenuOrder = 5, CSSClass = "fa fa-calendar", Enabled = true },
                //new MenuItem { MenuItemId = 9, MenuId = 2, Text = "Gallery Management", Action = "", Controller ="", URL = "#", MenuOrder = 9, CSSClass = "fa fa-folder", Enabled = true },

                 // Main Menus List - For Dealer Menus
                new MenuItem { MenuItemId = 15, MenuId = 3, Text = "Dashboard", Action = "", Controller ="", URL = "#", MenuOrder = 1, CSSClass = "fa fa-dashboard", Enabled = true },
                new MenuItem { MenuItemId = 16, MenuId = 3, Text = "Masters", Action = "", Controller ="", URL = "#", MenuOrder = 2, CSSClass = "fa fa-pie-chart", Enabled = true },
                new MenuItem { MenuItemId = 17, MenuId = 3, Text = "Alert Management", Action = "Index", Controller ="Alerts", URL = "", MenuOrder = 3, CSSClass = "fa fa-files-o", Enabled = true },
                new MenuItem { MenuItemId = 18, MenuId = 3, Text = "Reports", Action = "", Controller ="", URL = "#", MenuOrder = 4, CSSClass = "fa fa-th", Enabled = true },
                new MenuItem { MenuItemId = 19, MenuId = 3, Text = "Vehicles Online", Action = "", Controller ="", URL = "#", MenuOrder = 5, CSSClass = "fa fa-calendar", Enabled = true },
                
                 // Main Menus List - For Customer Menus
                new MenuItem { MenuItemId = 20, MenuId = 2, Text = "Dashboard", Action = "", Controller ="", URL = "#", MenuOrder = 1, CSSClass = "fa fa-dashboard", Enabled = true },
                new MenuItem { MenuItemId = 21, MenuId = 2, Text = "Trackng", Action = "", Controller ="", URL = "#", MenuOrder = 2, CSSClass = "fa fa-pie-chart", Enabled = true },
                new MenuItem { MenuItemId = 22, MenuId = 2, Text = "Alert Management", Action = "Index", Controller ="Alerts", URL = "", MenuOrder = 3, CSSClass = "fa fa-files-o", Enabled = true },
                new MenuItem { MenuItemId = 23, MenuId = 2, Text = "Reports", Action = "", Controller ="", URL = "#", MenuOrder = 4, CSSClass = "fa fa-files-o", Enabled = true },

                //Sub-Menus List
                //Children of Masters - Menu Id is 2
                new MenuItem { MenuItemId = 24, MenuId = 1, Text = "Distributor", Action = "Index", Controller ="Distributor", URL = "", MenuOrder = 1, ParentMenuId = 2, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 25, MenuId = 1, Text = "Dealer", Action = "Index", Controller ="Dealer", URL = "", MenuOrder = 2, ParentMenuId = 2, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 26, MenuId = 1, Text = "Customer", Action = "Index", Controller ="Customer", URL = "", MenuOrder = 3, ParentMenuId = 2, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 27, MenuId = 1, Text = "Vehicle", Action = "Index", Controller ="Vehicle", URL = "", MenuOrder = 4, ParentMenuId = 0, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 28, MenuId = 1, Text = "Device", Action = "Index", Controller ="Device", URL = "", MenuOrder = 5, ParentMenuId = 0, CSSClass = "", Enabled = true },

                //Sub-Menus List
                //Children of Masters - Menu Id is 11
                //new MenuItem { MenuItemId = 29, MenuId = 2, Text = "Distributor", Action = "Index", Controller ="Distributor", URL = "", MenuOrder = 1, ParentMenuId = 11, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 29, MenuId = 2, Text = "Dealer", Action = "Index", Controller ="Dealer", URL = "", MenuOrder = 1, ParentMenuId = 11, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 30, MenuId = 2, Text = "Customer", Action = "Index", Controller ="Customer", URL = "", MenuOrder = 2, ParentMenuId = 11, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 32, MenuId = 2, Text = "Vehicle", Action = "Index", Controller ="Vehicle", URL = "", MenuOrder = 4, ParentMenuId = 1, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 33, MenuId = 2, Text = "Device", Action = "Index", Controller ="Device", URL = "", MenuOrder = 5, ParentMenuId = 1, CSSClass = "", Enabled = true },

                 new MenuItem { MenuItemId = 31, MenuId = 3, Text = "Customer", Action = "Index", Controller ="Customer", URL = "", MenuOrder = 1, ParentMenuId = 16, CSSClass = "", Enabled = true },

                //Children of Alert Management - Menu Id is 16
                //new MenuItem { MenuItemId = 15, MenuId = 1, Text = "Sms Alert", Action = "Sms", Controller ="Alert", URL = "", MenuOrder = 1, ParentMenuId = 3, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 16, MenuId = 1, Text = "Mail Alert", Action = "Mail", Controller ="Alert", URL = "", MenuOrder = 2, ParentMenuId = 3, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 17, MenuId = 1, Text = "WhatsApp Alert", Action = "WhatsApp", Controller ="Alert", URL = "", MenuOrder = 3, ParentMenuId = 3, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 18, MenuId = 1, Text = "Client Details", Action = "Client", Controller ="Alert", URL = "", MenuOrder = 4, ParentMenuId = 3, CSSClass = "", Enabled = true },

                //Children of Reports - Menu Id is 4
                new MenuItem { MenuItemId = 32, MenuId = 1, Text = "Parking Report", Action = "ParkingReport", Controller ="Report", URL = "", MenuOrder = 1, ParentMenuId = 4, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 33, MenuId = 1, Text = "Speed Report", Action = "SpeedReport", Controller ="Report", URL = "", MenuOrder = 2, ParentMenuId = 4, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 34, MenuId = 1, Text = "OverSpeed Report", Action = "OverSpeedReport", Controller ="Report", URL = "", MenuOrder = 3, ParentMenuId = 4, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 35, MenuId = 1, Text = "Ignition Report", Action = "IgnitionReport", Controller ="Report", URL = "", MenuOrder = 4, ParentMenuId = 4, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 36, MenuId = 1, Text = "Daily Travelled", Action = "DailyTravel", Controller ="Report", URL = "", MenuOrder = 5, ParentMenuId = 4, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 37, MenuId = 1, Text = "Summary Report", Action = "Summary", Controller ="Report", URL = "", MenuOrder = 6, ParentMenuId = 4, CSSClass = "", Enabled = true },

                 //Children of Reports - Menu Id is 4
                new MenuItem { MenuItemId = 38, MenuId = 2, Text = "Parking Report", Action = "ParkingReport", Controller ="Report", URL = "", MenuOrder = 1, ParentMenuId = 13, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 39, MenuId = 2, Text = "Speed Report", Action = "SpeedReport", Controller ="Report", URL = "", MenuOrder = 2, ParentMenuId = 13, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 40, MenuId = 2, Text = "OverSpeed Report", Action = "OverSpeedReport", Controller ="Report", URL = "", MenuOrder = 3, ParentMenuId = 13, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 41, MenuId = 2, Text = "Ignition Report", Action = "IgnitionReport", Controller ="Report", URL = "", MenuOrder = 4, ParentMenuId = 13, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 42, MenuId = 2, Text = "Daily Travelled", Action = "DailyTravel", Controller ="Report", URL = "", MenuOrder = 5, ParentMenuId = 13, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 43, MenuId = 2, Text = "Summary Report", Action = "Summary", Controller ="Report", URL = "", MenuOrder = 6, ParentMenuId = 13, CSSClass = "", Enabled = true },

                 //Children of Reports - Menu Id is 4
                new MenuItem { MenuItemId = 44, MenuId = 3, Text = "Parking Report", Action = "ParkingReport", Controller ="Report", URL = "", MenuOrder = 1, ParentMenuId = 18, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 45, MenuId = 3, Text = "Speed Report", Action = "SpeedReport", Controller ="Report", URL = "", MenuOrder = 2, ParentMenuId = 18, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 46, MenuId = 3, Text = "OverSpeed Report", Action = "OverSpeedReport", Controller ="Report", URL = "", MenuOrder = 3, ParentMenuId = 18, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 47, MenuId = 3, Text = "Ignition Report", Action = "IgnitionReport", Controller ="Report", URL = "", MenuOrder = 4, ParentMenuId = 18, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 48, MenuId = 3, Text = "Daily Travelled", Action = "DailyTravel", Controller ="Report", URL = "", MenuOrder = 5, ParentMenuId = 18, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 49, MenuId = 3, Text = "Summary Report", Action = "Summary", Controller ="Report", URL = "", MenuOrder = 6, ParentMenuId = 18, CSSClass = "", Enabled = true },

                //Children of Reports - Menu Id is 4
                new MenuItem { MenuItemId = 50, MenuId = 4, Text = "Parking Report", Action = "ParkingReport", Controller ="Report", URL = "", MenuOrder = 1, ParentMenuId = 23, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 51, MenuId = 4, Text = "Speed Report", Action = "SpeedReport", Controller ="Report", URL = "", MenuOrder = 2, ParentMenuId = 23, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 52, MenuId = 4, Text = "OverSpeed Report", Action = "OverSpeedReport", Controller ="Report", URL = "", MenuOrder = 3, ParentMenuId = 23, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 53, MenuId = 4, Text = "Ignition Report", Action = "IgnitionReport", Controller ="Report", URL = "", MenuOrder = 4, ParentMenuId = 23, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 54, MenuId = 4, Text = "Daily Travelled", Action = "DailyTravel", Controller ="Report", URL = "", MenuOrder = 5, ParentMenuId = 23, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 55, MenuId = 4, Text = "Summary Report", Action = "Summary", Controller ="Report", URL = "", MenuOrder = 6, ParentMenuId = 23, CSSClass = "", Enabled = true },


                ////Children of User Management - Menu Id is 5
                //new MenuItem { MenuItemId = 56, MenuId = 1, Text = "User  Rights", Action = "UserRights", Controller ="UserMgmt", URL = "", MenuOrder = 1, ParentMenuId = 5, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 57, MenuId = 1, Text = "Distributor List", Action = "Distributor", Controller ="UserMgmt", URL = "", MenuOrder = 2, ParentMenuId = 5, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 58, MenuId = 1, Text = "GEO Fence", Action = "GeoFence", Controller ="UserMgmt", URL = "", MenuOrder = 3, ParentMenuId = 5, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 59, MenuId = 1, Text = "Operator List", Action = "Operator", Controller ="UserMgmt", URL = "", MenuOrder = 4, ParentMenuId = 5, CSSClass = "", Enabled = true },

                ////Children of Categories Management - Menu Id is 6
                //new MenuItem { MenuItemId = 60, MenuId = 1, Text = "Sms Management", Action = "Sms", Controller ="CategoriesMgmt", URL = "", MenuOrder = 1, ParentMenuId = 6, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 61, MenuId = 1, Text = "Sms Credit Management", Action = "SmsCredit", Controller ="CategoriesMgmt", URL = "", MenuOrder = 2, ParentMenuId = 6, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 62, MenuId = 1, Text = "Bonding Management", Action = "Bonding", Controller ="CategoriesMgmt", URL = "", MenuOrder = 3, ParentMenuId = 6, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 63, MenuId = 1, Text = "Access Management", Action = "Access", Controller ="CategoriesMgmt", URL = "", MenuOrder = 4, ParentMenuId = 6, CSSClass = "", Enabled = true },

                ////Children of Server  Management - Menu Id is 7
                //new MenuItem { MenuItemId = 64, MenuId = 1, Text = "Server Renual", Action = "Server", Controller ="ServerMgmt", URL = "", MenuOrder = 1, ParentMenuId = 7, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 65, MenuId = 1, Text = "Distributor Renual", Action = "Distributor", Controller ="ServerMgmt", URL = "", MenuOrder = 2, ParentMenuId = 7, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 66, MenuId = 1, Text = "Dealer Renual", Action = "Dealer", Controller ="ServerMgmt", URL = "", MenuOrder = 3, ParentMenuId = 7, CSSClass = "", Enabled = true },
                //new MenuItem { MenuItemId = 67, MenuId = 1, Text = "Device Renual", Action = "Device", Controller ="ServerMgmt", URL = "", MenuOrder = 4, ParentMenuId = 7, CSSClass = "", Enabled = true },

                //Children of Vehicle Online - Menu Id is 8
                new MenuItem { MenuItemId = 56, MenuId = 1, Text = "Two Wheelers", Action = "TwoWheelers", Controller ="VehiclesOnline", URL = "", MenuOrder = 1, ParentMenuId = 8, CSSClass = "", Enabled = true },
                new MenuItem { MenuItemId = 57, MenuId = 1, Text = "Four Wheelers", Action = "FourWheelers", Controller ="VehiclesOnline", URL = "", MenuOrder = 2, ParentMenuId = 8, CSSClass = "", Enabled = true },
            };

            context.MenuItems.AddRange(menuItems);

            List<RoleMenu> roleMenuItems = new List<RoleMenu>()
            {
                new RoleMenu() { RoleMenuId = 1, RoleId = 1, MenuId = 1, Enabled = true },
                new RoleMenu() { RoleMenuId = 2, RoleId = 2, MenuId = 2, Enabled = true },
                new RoleMenu() { RoleMenuId = 3, RoleId = 3, MenuId = 3, Enabled = true },
                new RoleMenu() { RoleMenuId = 4, RoleId = 4, MenuId = 4, Enabled = true }
            };

            context.RoleMenus.AddRange(roleMenuItems);
        }

        private void CreateUsers(TMSEntities context)
        {
            CreateAdmins(context);
            //CreateDistributors(context);
        }

        private void CreateAdmins(TMSEntities context)
        {
            Address adminAddress = new Address() { AddressLine1 = "Door No. 6", AddressLine2 = "Nethaji Street", AddressLine3 = "Porur", City = "Chennai", State = "Tamil Nadu", Country = "India", PostalCode = "600089"};
            Admin adminMadankumar = new Admin() { FirstName = "Madankumar", LastName = "Angusamy", Email = "madankumar6@gmail.com", UserId = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF"), Username = "madan", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = adminAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "8122163462", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("00000000-0000-0000-0000-000000000000") };
            Admin adminRamesh = new Admin() { FirstName = "Ramesh", LastName = "Karuppanan", Email = "iamkramesh@gmail.com", UserId = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB"), Username = "ramesh", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = adminAddress, CompanyName = "NoobieCode - Ramesh", PhoneNo = "9943225335", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("00000000-0000-0000-0000-000000000000") };

            context.Users.Add(adminMadankumar);
            context.Users.Add(adminRamesh);
        }

        private void CreateDistributors(TMSEntities context)
        {
            Address distributorAddress = new Address() { AddressLine1 = "Door No. 8", AddressLine2 = "Bharathi Street", AddressLine3 = "RA Puram", City = "Coimbatore", State = "Tamil Nadu", Country = "India", PostalCode = "600134" };
            //For admin - Madankumar
            List<Distributor> distributorsForMadankumar = new List<Distributor>()
            {
                new Distributor() { FirstName = "Sakthi", LastName = "GASC", Email = "sakthi@gmail.com", Username = "sakthi", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo =   "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF"), UserId = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E")},
                new Distributor() { FirstName = "Sakthi1", LastName = "GASC", Email = "sakthi1@gmail.com", Username = "sakthi1", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi2", LastName = "GASC", Email = "sakthi2@gmail.com", Username = "sakthi2", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi3", LastName = "GASC", Email = "sakthi3@gmail.com", Username = "sakthi3", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi4", LastName = "GASC", Email = "sakthi4@gmail.com", Username = "sakthi4", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi5", LastName = "GASC", Email = "sakthi5@gmail.com", Username = "sakthi5", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi6", LastName = "GASC", Email = "sakthi6@gmail.com", Username = "sakthi6", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi7", LastName = "GASC", Email = "sakthi7@gmail.com", Username = "sakthi7", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi8", LastName = "GASC", Email = "sakthi8@gmail.com", Username = "sakthi8", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi9", LastName = "GASC", Email = "sakthi9@gmail.com", Username = "sakthi9", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi10", LastName = "GASC", Email = "sakthi10@gmail.com", Username = "sakthi10", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi11", LastName = "GASC", Email = "sakthi11@gmail.com", Username = "sakthi11", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi12", LastName = "GASC", Email = "sakthi12@gmail.com", Username = "sakthi12", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi13", LastName = "GASC", Email = "sakthi13@gmail.com", Username = "sakthi13", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi14", LastName = "GASC", Email = "sakthi14@gmail.com", Username = "sakthi14", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi15", LastName = "GASC", Email = "sakthi15@gmail.com", Username = "sakthi15", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi16", LastName = "GASC", Email = "sakthi16@gmail.com", Username = "sakthi16", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi17", LastName = "GASC", Email = "sakthi17@gmail.com", Username = "sakthi17", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi18", LastName = "GASC", Email = "sakthi18@gmail.com", Username = "sakthi18", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi19", LastName = "GASC", Email = "sakthi19@gmail.com", Username = "sakthi19", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi20", LastName = "GASC", Email = "sakthi20@gmail.com", Username = "sakthi20", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi21", LastName = "GASC", Email = "sakthi21@gmail.com", Username = "sakthi21", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi22", LastName = "GASC", Email = "sakthi22@gmail.com", Username = "sakthi22", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi23", LastName = "GASC", Email = "sakthi23@gmail.com", Username = "sakthi23", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi24", LastName = "GASC", Email = "sakthi24@gmail.com", Username = "sakthi24", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi25", LastName = "GASC", Email = "sakthi25@gmail.com", Username = "sakthi25", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi26", LastName = "GASC", Email = "sakthi26@gmail.com", Username = "sakthi26", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi27", LastName = "GASC", Email = "sakthi27@gmail.com", Username = "sakthi27", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi28", LastName = "GASC", Email = "sakthi28@gmail.com", Username = "sakthi28", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi29", LastName = "GASC", Email = "sakthi29@gmail.com", Username = "sakthi29", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi30", LastName = "GASC", Email = "sakthi30@gmail.com", Username = "sakthi30", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi31", LastName = "GASC", Email = "sakthi31@gmail.com", Username = "sakthi31", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi32", LastName = "GASC", Email = "sakthi32@gmail.com", Username = "sakthi32", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi33", LastName = "GASC", Email = "sakthi33@gmail.com", Username = "sakthi33", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi34", LastName = "GASC", Email = "sakthi34@gmail.com", Username = "sakthi34", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi35", LastName = "GASC", Email = "sakthi35@gmail.com", Username = "sakthi35", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi36", LastName = "GASC", Email = "sakthi36@gmail.com", Username = "sakthi36", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi37", LastName = "GASC", Email = "sakthi37@gmail.com", Username = "sakthi37", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi38", LastName = "GASC", Email = "sakthi38@gmail.com", Username = "sakthi38", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi39", LastName = "GASC", Email = "sakthi39@gmail.com", Username = "sakthi39", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") },
                new Distributor() { FirstName = "Sakthi40", LastName = "GASC", Email = "sakthi40@gmail.com", Username = "sakthi40", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Madan", PhoneNo = "9626167210", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("A3819085-5116-42DD-9DF3-461953A10BCF") }
            };                                                                                                         
            //For admin - Ramesh                                                                                   
            List<Distributor> distributorsForRamesh = new List<Distributor>()                                      
            {
                new Distributor() { FirstName = "Dinesh", LastName = "GASC", Email = "dinesh@gmail.com",  Username = "dinesh", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh1", LastName = "GASC", Email = "dinesh1@gmail.com", Username = "dinesh1", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh2", LastName = "GASC", Email = "dinesh2@gmail.com", Username = "dinesh2", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh3", LastName = "GASC", Email = "dinesh3@gmail.com", Username = "dinesh3", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh4", LastName = "GASC", Email = "dinesh4@gmail.com", Username = "dinesh4", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh5", LastName = "GASC", Email = "dinesh5@gmail.com", Username = "dinesh5", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh6", LastName = "GASC", Email = "dinesh6@gmail.com", Username = "dinesh6", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh7", LastName = "GASC", Email = "dinesh7@gmail.com", Username = "dinesh7", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh8", LastName = "GASC", Email = "dinesh8@gmail.com", Username = "dinesh8", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh9", LastName = "GASC", Email = "dinesh9@gmail.com", Username = "dinesh9", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh10", LastName = "GASC", Email = "dinesh10@gmail.com", Username = "dinesh10", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh11", LastName = "GASC", Email = "dinesh11@gmail.com", Username = "dinesh11", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh12", LastName = "GASC", Email = "dinesh12@gmail.com", Username = "dinesh12", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh13", LastName = "GASC", Email = "dinesh13@gmail.com", Username = "dinesh13", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh14", LastName = "GASC", Email = "dinesh14@gmail.com", Username = "dinesh14", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh15", LastName = "GASC", Email = "dinesh15@gmail.com", Username = "dinesh15", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh16", LastName = "GASC", Email = "dinesh16@gmail.com", Username = "dinesh16", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh17", LastName = "GASC", Email = "dinesh17@gmail.com", Username = "dinesh17", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh18", LastName = "GASC", Email = "dinesh18@gmail.com", Username = "dinesh18", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh19", LastName = "GASC", Email = "dinesh19@gmail.com", Username = "dinesh19", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh20", LastName = "GASC", Email = "dinesh20@gmail.com", Username = "dinesh20", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh21", LastName = "GASC", Email = "dinesh21@gmail.com", Username = "dinesh21", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh22", LastName = "GASC", Email = "dinesh22@gmail.com", Username = "dinesh22", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh23", LastName = "GASC", Email = "dinesh23@gmail.com", Username = "dinesh23", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh24", LastName = "GASC", Email = "dinesh24@gmail.com", Username = "dinesh24", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh25", LastName = "GASC", Email = "dinesh25@gmail.com", Username = "dinesh25", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh26", LastName = "GASC", Email = "dinesh26@gmail.com", Username = "dinesh26", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh27", LastName = "GASC", Email = "dinesh27@gmail.com", Username = "dinesh27", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh28", LastName = "GASC", Email = "dinesh28@gmail.com", Username = "dinesh28", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh29", LastName = "GASC", Email = "dinesh29@gmail.com", Username = "dinesh29", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh30", LastName = "GASC", Email = "dinesh30@gmail.com", Username = "dinesh30", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh31", LastName = "GASC", Email = "dinesh31@gmail.com", Username = "dinesh31", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh32", LastName = "GASC", Email = "dinesh32@gmail.com", Username = "dinesh32", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh33", LastName = "GASC", Email = "dinesh33@gmail.com", Username = "dinesh33", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh34", LastName = "GASC", Email = "dinesh34@gmail.com", Username = "dinesh34", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh35", LastName = "GASC", Email = "dinesh35@gmail.com", Username = "dinesh35", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh36", LastName = "GASC", Email = "dinesh36@gmail.com", Username = "dinesh36", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh37", LastName = "GASC", Email = "dinesh37@gmail.com", Username = "dinesh37", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh38", LastName = "GASC", Email = "dinesh38@gmail.com", Username = "dinesh38", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh39", LastName = "GASC", Email = "dinesh39@gmail.com", Username = "dinesh39", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") },
                new Distributor() { FirstName = "Dinesh40", LastName = "GASC", Email = "dinesh40@gmail.com", Username = "dinesh40", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Dinesh", PhoneNo = "7502337565", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("BA5EF4FB-36F9-4B46-9EE4-C2E4C0D0F8CB") }
            };

            //For admin - Ramesh                                                                                   
            List<Dealer> dealersForSakthi = new List<Dealer>()
            {
                new Dealer() { FirstName = "Pradeep", LastName = "GASC", Email = "Pradeep@gmail.com",  Username = "pradeep", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep1", LastName = "GASC", Email = "Pradeep1@gmail.com", Username = "pradeep1", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep2", LastName = "GASC", Email = "Pradeep2@gmail.com", Username = "pradeep2", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep3", LastName = "GASC", Email = "Pradeep3@gmail.com", Username = "pradeep3", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep4", LastName = "GASC", Email = "Pradeep4@gmail.com", Username = "pradeep4", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep5", LastName = "GASC", Email = "Pradeep5@gmail.com", Username = "pradeep5", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep6", LastName = "GASC", Email = "Pradeep6@gmail.com", Username = "pradeep6", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep7", LastName = "GASC", Email = "Pradeep7@gmail.com", Username = "pradeep7", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep8", LastName = "GASC", Email = "Pradeep8@gmail.com", Username = "pradeep8", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep9", LastName = "GASC", Email = "Pradeep9@gmail.com", Username = "pradeep9", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep10", LastName = "GASC", Email = "Pradeep10@gmail.com", Username = "pradeep10", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep11", LastName = "GASC", Email = "Pradeep11@gmail.com", Username = "pradeep11", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep12", LastName = "GASC", Email = "Pradeep12@gmail.com", Username = "pradeep12", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep13", LastName = "GASC", Email = "Pradeep13@gmail.com", Username = "pradeep13", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep14", LastName = "GASC", Email = "Pradeep14@gmail.com", Username = "pradeep14", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep15", LastName = "GASC", Email = "Pradeep15@gmail.com", Username = "pradeep15", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep16", LastName = "GASC", Email = "Pradeep16@gmail.com", Username = "pradeep16", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep17", LastName = "GASC", Email = "Pradeep17@gmail.com", Username = "pradeep17", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep18", LastName = "GASC", Email = "Pradeep18@gmail.com", Username = "pradeep18", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep19", LastName = "GASC", Email = "Pradeep19@gmail.com", Username = "pradeep19", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep20", LastName = "GASC", Email = "Pradeep20@gmail.com", Username = "pradeep20", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep21", LastName = "GASC", Email = "Pradeep21@gmail.com", Username = "pradeep21", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep22", LastName = "GASC", Email = "Pradeep22@gmail.com", Username = "pradeep22", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep23", LastName = "GASC", Email = "Pradeep23@gmail.com", Username = "pradeep23", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep24", LastName = "GASC", Email = "Pradeep24@gmail.com", Username = "pradeep24", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep25", LastName = "GASC", Email = "Pradeep25@gmail.com", Username = "pradeep25", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep26", LastName = "GASC", Email = "Pradeep26@gmail.com", Username = "pradeep26", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep27", LastName = "GASC", Email = "Pradeep27@gmail.com", Username = "pradeep27", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep28", LastName = "GASC", Email = "Pradeep28@gmail.com", Username = "pradeep28", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep29", LastName = "GASC", Email = "Pradeep29@gmail.com", Username = "pradeep29", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep30", LastName = "GASC", Email = "Pradeep30@gmail.com", Username = "pradeep30", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep31", LastName = "GASC", Email = "Pradeep31@gmail.com", Username = "pradeep31", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep32", LastName = "GASC", Email = "Pradeep32@gmail.com", Username = "pradeep32", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep33", LastName = "GASC", Email = "Pradeep33@gmail.com", Username = "pradeep33", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep34", LastName = "GASC", Email = "Pradeep34@gmail.com", Username = "pradeep34", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep35", LastName = "GASC", Email = "Pradeep35@gmail.com", Username = "pradeep35", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep36", LastName = "GASC", Email = "Pradeep36@gmail.com", Username = "pradeep36", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep37", LastName = "GASC", Email = "Pradeep37@gmail.com", Username = "pradeep37", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep38", LastName = "GASC", Email = "Pradeep38@gmail.com", Username = "pradeep38", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep39", LastName = "GASC", Email = "Pradeep39@gmail.com", Username = "pradeep39", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") },
                new Dealer() { FirstName = "Pradeep40", LastName = "GASC", Email = "Pradeep40@gmail.com", Username = "pradeep40", Password = "$MYHASH$V1$10000$VxlBfNDOtId/3lGtWzJ3KnSLbACm5sHwgqdijokzg194S7S8", Address = distributorAddress, CompanyName = "NoobieCode - Pradeep", PhoneNo = "9976456312", Status = true, WebSite = "http://www.noobiecode.com", Parent = Guid.Parse("D44FD790-8A3B-4908-B24A-768B64483D4E") }
            };

            context.Users.AddRange(distributorsForMadankumar);
            context.Users.AddRange(distributorsForRamesh);
            context.Users.AddRange(dealersForSakthi);
        }

        public override void InitializeDatabase(TMSEntities context)
        {
            bool ex = (bool)context.Database.Exists();
            if (!ex)
            {
                context.Database.Create();
                //Seed(context); // Avoid this by doing it on EF config way
            }
            base.InitializeDatabase(context);
        }
    }
}
